### ISSUE TITLE
Fixed Detail Layout ( and others ) 

### ISSUE THREAD

**Issue by tsanyqudsi** [osososps/pppooolll#2]
commit https://github.com/osososps/pppooolll/commit/b905e0d38300465ec070e1ef0b72ce85433d3a30 harusnya beresin :

1. glitch dropdown ( yang kita urusin untuk mirip esterchoi, skrg udah bisa tembus kliknya ).
2. Random banner di detail page, ( Soalnya kalau gambar pertama a bit issue ).
3. Spacing ?
4. Sedikit efek transparansi. ( yang request warna beda, FYI. It's a bit tricky despite sebetulnya di CSS ada. Dunno why it didn't work as intended jadi gue pake workaround ).
5. Persiapan untuk screensaver-ish ( based on #1 )

**Comment by pppooolll** [comment]
1. OK.
2. Ini kayaknya gpp.
3. Buat footer? kurang lebih kayak navigasi.
4. Jangan kasih efek lagi. Kayak sebelumnya aja udah polos. Jadi aneh.
5. OK.
